In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]

In [5]:
arr.shape

(5,)

In [6]:
series = pd.Series([10,20,30,40,50])
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
csv=pd.read_csv("C:/Users/vasan/Downloads/archive (1).zip")

In [8]:
print(csv)

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0
1               2  38.0   71.2833    1      1     0       0       0       0
2               3  26.0    7.9250    1      0     0       0       0       0
3               4  35.0   53.1000    1      1     0       0       0       0
4               5  35.0    8.0500    0      0     0       0       0       0
...           ...   ...       ...  ...    ...   ...     ...     ...     ...
1304         1305  28.0    8.0500    0      0     0       0       0       0
1305         1306  39.0  108.9000    1      0     0       0       0       0
1306         1307  38.5    7.2500    0      0     0       0       0       0
1307         1308  28.0    8.0500    0      0     0       0       0       0
1308         1309  28.0   22.3583    0      1     0       0       0       0

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
0          0  ...        0        0        0       3        0        0
1          0  ...        0        0        0       1        0        0
2          0  ...        0        0        0       3        0        0
3          0  ...        0        0        0       1        0        0
4          0  ...        0        0        0       3        0        0
...      ...  ...      ...      ...      ...     ...      ...      ...
1304       0  ...        0        0        0       3        0        0
1305       0  ...        0        0        0       1        0        0
1306       0  ...        0        0        0       3        0        0
1307       0  ...        0        0        0       3        0        0
1308       0  ...        0        0        0       3        0        0

      Embarked  zero.17  zero.18  2urvived
0          2.0        0        0         0
1          0.0        0        0         1
2          2.0        0        0         1
3          2.0        0        0         1
4          2.0        0        0         0
...        ...      ...      ...       ...
1304       2.0        0        0         0
1305       0.0        0        0         0
1306       2.0        0        0         0
1307       2.0        0        0         0
1308       0.0        0        0         0

[1309 rows x 28 columns]

In [9]:
csv.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [10]:
csv.tail()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [ ]:
shape